import { clean, json } from "./_gateway.js";
import { assignment, qualityLab } from "./_event.js";

const MODELS = new Set(["Decision Tree", "Logistic Regression", "K-Nearest Neighbors", "Random Forest", "Support Vector Machine"]);
const configured = () => Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_SECRET_KEY);
async function consumeEvaluation(room, player) {
  if (!configured()) return null;
  const response = await fetch(`${process.env.SUPABASE_URL}/rest/v1/rpc/use_game_evaluation`, { method: "POST", headers: { "Content-Type": "application/json", apikey: process.env.SUPABASE_SECRET_KEY, Authorization: `Bearer ${process.env.SUPABASE_SECRET_KEY}` }, body: JSON.stringify({ room_pin: room, player_name: player }) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw Error(body.message || "Could not reserve evaluation");
  return body;
}
const vote = values => { const counts = {}; values.forEach(value => counts[value] = (counts[value] || 0) + 1); return Object.entries(counts).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0][0]; };
const rng = seed => () => ((seed = Math.imul(seed, 1664525) + 1013904223 >>> 0) / 4294967296);
function scaler(rows, features) { const means = features.map(f => rows.reduce((n, row) => n + Number(row[f]), 0) / rows.length); const deviations = features.map((f, i) => Math.sqrt(rows.reduce((n, row) => n + (Number(row[f]) - means[i]) ** 2, 0) / rows.length) || 1); return row => features.map((f, i) => (Number(row[f]) - means[i]) / deviations[i]); }
const gini = labels => { const counts = {}; labels.forEach(x => counts[x] = (counts[x] || 0) + 1); return 1 - Object.values(counts).reduce((n, count) => n + (count / labels.length) ** 2, 0); };
function bestSplit(X, y, columns) { let best; for (const j of columns) { const values = [...new Set(X.map(row => row[j]))].sort((a, b) => a - b); const stride = Math.max(1, Math.floor(values.length / 24)); for (let i = stride; i < values.length; i += stride) { const cut = (values[i - 1] + values[i]) / 2, left = [], right = []; X.forEach((row, n) => (row[j] <= cut ? left : right).push(y[n])); if (!left.length || !right.length) continue; const score = (left.length * gini(left) + right.length * gini(right)) / y.length; if (!best || score < best.score) best = { j, cut, score }; } } return best; }
function growTree(X, y, columns, depth = 0, maxDepth = 5) { const majority = vote(y); if (depth >= maxDepth || new Set(y).size === 1 || X.length < 5) return { label: majority }; const split = bestSplit(X, y, columns); if (!split) return { label: majority }; const lX = [], ly = [], rX = [], ry = []; X.forEach((row, i) => { if (row[split.j] <= split.cut) { lX.push(row); ly.push(y[i]); } else { rX.push(row); ry.push(y[i]); } }); return { ...split, label: majority, left: growTree(lX, ly, columns, depth + 1, maxDepth), right: growTree(rX, ry, columns, depth + 1, maxDepth) }; }
const traverse = (node, row) => node.label && !node.left ? node.label : traverse(row[node.j] <= node.cut ? node.left : node.right, row);
function treeFit(X, y) { const root = growTree(X, y, X[0].map((_, i) => i)); return row => traverse(root, row); }
function forestFit(X, y) { const random = rng(X.length * 1009 + X[0].length * 97), trees = []; for (let tree = 0; tree < 11; tree++) { const sampleX = [], sampleY = []; for (let i = 0; i < X.length; i++) { const at = Math.floor(random() * X.length); sampleX.push(X[at]); sampleY.push(y[at]); } const columns = [...X[0].keys()].sort(() => random() - .5).slice(0, Math.max(1, Math.floor(Math.sqrt(X[0].length)))); trees.push(growTree(sampleX, sampleY, columns, 0, 6)); } return row => vote(trees.map(tree => traverse(tree, row))); }
function knnPredict(X, y, row, k = 7) { return vote(X.map((x, i) => ({ label: y[i], distance: x.reduce((n, value, j) => n + (value - row[j]) ** 2, 0) })).sort((a, b) => a.distance - b.distance).slice(0, Math.min(k, X.length)).map(x => x.label)); }
function logisticFit(X, y) {
  const labels = [...new Set(y)].sort(), weights = labels.map(() => Array(X[0].length + 1).fill(0));
  for (let epoch = 0; epoch < 280; epoch++) {
    const rate = .12 / (1 + epoch / 80);
    X.forEach((row, index) => {
      const input = [1, ...row], logits = weights.map(weight => weight.reduce((sum, value, i) => sum + value * input[i], 0));
      const maximum = Math.max(...logits), exponentials = logits.map(value => Math.exp(Math.max(-30, value - maximum))), total = exponentials.reduce((a, b) => a + b, 0);
      weights.forEach((weight, classIndex) => weight.forEach((value, i) => { const error = exponentials[classIndex] / total - (y[index] === labels[classIndex] ? 1 : 0); weight[i] = value - rate * (error * input[i] + .0008 * value); }));
    });
  }
  return row => { const input = [1, ...row], scores = weights.map(weight => weight.reduce((sum, value, i) => sum + value * input[i], 0)); return labels[scores.indexOf(Math.max(...scores))]; };
}
function svmFit(X, y) {
  const labels = [...new Set(y)].sort(), weights = labels.map(() => Array(X[0].length + 1).fill(0));
  for (let epoch = 0; epoch < 220; epoch++) {
    const rate = .045 / (1 + epoch / 65);
    X.forEach((row, index) => { const input = [1, ...row]; weights.forEach((weight, classIndex) => { const target = y[index] === labels[classIndex] ? 1 : -1, margin = target * weight.reduce((sum, value, i) => sum + value * input[i], 0); weight.forEach((value, i) => weight[i] = value * (1 - rate * .004) + (margin < 1 ? rate * target * input[i] : 0)); }); });
  }
  return row => { const input = [1, ...row], scores = weights.map(weight => weight.reduce((sum, value, i) => sum + value * input[i], 0)); return labels[scores.indexOf(Math.max(...scores))]; };
}
function modelPredictor(model, X, y) { if (model === "K-Nearest Neighbors") return row => knnPredict(X, y, row); if (model === "Decision Tree") return treeFit(X, y); if (model === "Random Forest") return forestFit(X, y); if (model === "Logistic Regression") return logisticFit(X, y); return svmFit(X, y); }
function macroF1(actual, predicted) { const labels = [...new Set([...actual, ...predicted])]; return labels.reduce((sum, label) => { const tp = actual.filter((x, i) => x === label && predicted[i] === label).length, fp = actual.filter((x, i) => x !== label && predicted[i] === label).length, fn = actual.filter((x, i) => x === label && predicted[i] !== label).length; return sum + (2 * tp / (2 * tp + fp + fn || 1)); }, 0) / labels.length; }
function applyRepairs(event, submittedLabels, repairNames) { const labels = { ...submittedLabels }, cleanRows = [...event.known, ...event.unknown], rows = qualityLab(event).map((row, index) => ({ ...row, target: index < 150 ? row.target : labels[row.id] })); if (repairNames.includes("repair suspicious label #014")) rows[163].target = event.unknown[13].target; if (repairNames.includes("repair suspicious label #039")) rows[188].target = event.unknown[38].target; if (repairNames.includes("impute residual sugar")) { const values = rows.map(row => row.residual_sugar).filter(Number.isFinite).sort((a, b) => a - b), median = values[Math.floor(values.length / 2)]; rows.forEach(row => { if (!Number.isFinite(row.residual_sugar)) row.residual_sugar = median; }); } if (repairNames.includes("clip chlorides outliers")) { const sorted = rows.map(r => r.chlorides).sort((a, b) => a - b), low = sorted[Math.floor(sorted.length * .01)], high = sorted[Math.floor(sorted.length * .99)]; rows.forEach(row => row.chlorides = Math.min(high, Math.max(low, row.chlorides))); } if (repairNames.includes("remove duplicate group A")) rows[61] = { ...cleanRows[61], target: cleanRows[61].target }; if (repairNames.includes("remove duplicate group B")) rows[119] = { ...cleanRows[119], target: cleanRows[119].target }; return rows; }
function run(model, features, working, hidden) { const validation = working.filter((_, i) => i % 5 === 0), training = working.filter((_, i) => i % 5 !== 0), toTrain = scaler(training, features), toWorking = scaler(working, features), predictor = modelPredictor(model, training.map(toTrain), training.map(row => row.target)), score = macroF1(validation.map(row => row.target), validation.map(row => predictor(toTrain(row)))); const submitPredictor = modelPredictor(model, working.map(toWorking), working.map(row => row.target)); return { score, predictions: hidden.map(row => submitPredictor(toWorking(row))) }; }

export default async function handler(req, res) { if (req.method !== "POST") return json(res, 405, { error: "POST required" }); const room = clean(req.body?.room, 16), player = clean(req.body?.player, 20), action = clean(req.body?.action, 12), model = String(req.body?.model || ""), features = req.body?.features, repairNames = Array.isArray(req.body?.repairs) ? req.body.repairs.map(x => clean(x, 48)) : []; if (!room || !MODELS.has(model)) return json(res, 400, { error: "Choose one approved model" }); if (!Array.isArray(features) || features.length !== 8 || new Set(features).size !== 8) return json(res, 400, { error: "Select exactly 8 unique features" }); const event = assignment(room); if (!features.every(feature => event.features.includes(feature))) return json(res, 400, { error: "Invalid feature selection" }); const labels = req.body?.labels || {}; if (event.unknown.some(row => !labels[row.id]) || Object.values(labels).some(label => !event.known.some(row => row.target === label))) return json(res, 400, { error: "All 50 labels must use an allowed class" }); try { const working = applyRepairs(event, labels, repairNames), result = run(model, features, working, event.hidden); if (action === "evaluate") { if (!player) return json(res, 400, { error: "Player identity required" }); const usedEvaluations = await consumeEvaluation(room, player); return json(res, 200, { model, metric: "Macro F1", score: Number(result.score.toFixed(3)), fixedValidationRecords: 40, usedEvaluations, evaluationLimit: 8 }); } if (action === "submit") return json(res, 200, { model, metric: "Macro F1", validationScore: Number(result.score.toFixed(3)), csv: ["id,prediction", ...event.hidden.map((row, i) => `${row.id},${result.predictions[i]}`)].join("\n") }); return json(res, 400, { error: "unknown action" }); } catch (error) { const message = error.message.includes("EVALUATION_LIMIT") ? "You have used all 8 validation runs" : error.message.includes("GAME_NOT_ACTIVE") ? "Game is not active" : error.message; return json(res, 409, { error: message }); } }
